# CLUSTER=draco NUM_RUNS=5 BATCH_SIZE=8 GRAD_ACCUMULATION=1 NUM_NODES=2 EXP_BASE_NAME="2_Beta_122M_ctc" PROJECT="QN_2.0" ./Expmod.sh
# CLUSTER=draco NUM_RUNS=5 BATCH_SIZE=8 GRAD_ACCUMULATION=1 NUM_NODES=2 EXP_BASE_NAME="5_Beta_1_sam_str4_M_ctc" PROJECT="QN_2.0" ./Expmod.sh
# CLUSTER=draco NUM_RUNS=5 BATCH_SIZE=8 GRAD_ACCUMULATION=1 NUM_NODES=2 EXP_BASE_NAME="5_Beta_2_sam_str4_M_no_joint_ctc" PROJECT="QN_2.0" ./Expmod.sh
# CLUSTER=draco NUM_RUNS=5 BATCH_SIZE=8 GRAD_ACCUMULATION=1 NUM_NODES=2 EXP_BASE_NAME="5_Beta_2_Conformer_no_attention_98M_bpe_ctc" PROJECT="QN_2.0" ./Expmod_bpe.sh
# CLUSTER=draco NUM_RUNS=5 BATCH_SIZE=8 GRAD_ACCUMULATION=1 NUM_NODES=2 EXP_BASE_NAME="5_Beta_3_sam_str4_M_no_joint_ctc" PROJECT="QN_2.0" ./Expmod.sh
# CLUSTER=draco NUM_RUNS=5 BATCH_SIZE=8 GRAD_ACCUMULATION=1 NUM_NODES=2 EXP_BASE_NAME="6_Beta_4_Conformer_no_attention_98M_bpe_ctc" PROJECT="QN_2.0" ./Expmod_bpe_conf_no_att.sh
CLUSTER=draco NUM_RUNS=5 BATCH_SIZE=8 GRAD_ACCUMULATION=1 NUM_NODES=2 EXP_BASE_NAME="A-Test_13_Conformer_no_attention_bpe_ctc_novograd" PROJECT="QN_2.0" ./Expmod_bpe_conf_no_att.sh
